#pragma once

#define TAP_CODE_DELAY 5

/* Reduce firmware size */
#define LAYER_STATE_8BIT
#define NO_ACTION_ONESHOT

#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define TAPPING_TERM 185
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY

#define MOUSE_EXTENDED_REPORT

#define MOUSEKEY_INTERVAL 10
#define MOUSEKEY_MOVE_DELTA 2
#define MOUSEKEY_MAX_SPEED 14
#define MOUSEKEY_TIME_TO_MAX 80

#define MOUSEKEY_WHEEL_DELTA 1
