name: Build my userspace

permissions:
  contents: read
  actions: write

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  KEYMAP: fj88_36_shingeta

jobs:

  build_targets:
    name: "Compile ${{ env.KEYMAP }}"
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    continue-on-error: true

    steps:
      - name: Disable safe.directory check
        run: |
          git config --global --add safe.directory '*'

      - name: Checkout QMK Firmware
        uses: actions/checkout@v4

      - name: Deploy submodules
        run: |
          qmk git-submodule -f

      - name: Build targets
        continue-on-error: true
        run: |
          export NCPUS=$(( $(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null) -1 ))
          qmk mass-compile -t -j $NCPUS -e DUMP_CI_METADATA=yes $(qmk find -km ${{ env.KEYMAP }}) || touch .failed

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ env.KEYMAP }}
          if-no-files-found: ignore
          path: |
            *.bin
            *.hex
            *.uf2
            .build/failed.*
            .failed

      - name: Fail build if any group failed
        run: |
          # Exit with failure if the compilation stage failed
          [ ! -f .failed ] || exit 1
